Improved CircleCI config - test1

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -4,16 +4,56 @@ orbs:
   aws-cli: circleci/aws-cli@3.1
 
 jobs:
-  build:
+  database-snapshot:
+    parameters:
+      stack_name:
+        description: "CloudFormation stack name"
+        type: string
     working_directory: /home/circleci/app
+    docker:
+      - image: cimg/base:current
+    steps:
+      - checkout
+      - setup_remote_docker
+      - aws-cli/setup:
+          role-arn: "arn:aws:iam::$ORG_AWS_ACCOUNT_ID:role/CircleCI-OIDC-Connect"
+          profile-name: "OIDC-Profile"
+          role-session-name: "database-snapshot"
+          session-duration: "1800"
+      - run:
+          name: Get RDS Instance ID
+          command: |
+            RDS_ID=$(aws rds describe-db-instances --query 'DBInstances[?contains(TagList[].Key, `aws:cloudformation:stack-name`) && contains(TagList[].Value, `tasking-manager-<< parameters.stack_name >>'`)].[DBInstanceIdentifier]' --output text)
+            echo "export RDS_ID=$RDS_ID" >> $BASH_ENV
+      - run:
+          name: Backup the database
+          no_output_timeout: 15m
+          command: |
+            TIME_NOW=$(date --utc '+%s')
+            aws rds create-db-snapshot \
+                        --db-snapshot-identifier << parameters.stack_name >>-${RDS_ID}-${TIME_NOW} \
+                        --db-instance-identifier ${RDS_ID} \
+                        --tags Key=stack_name,Value=<< parameters.stack_name >> Key=unix_utc_epoch,Value=$(date --utc '+%s')
+            aws rds wait db-snapshot-completed \
+                        --db-snapshot-identifier << parameters.stack_name >>-${RDS_ID}-${TIME_NOW} \
+                        --db-instance-identifier ${RDS_ID}
+            if [[ $? -eq 255 ]]; then
+              echo "Production snapshot creation failed. Exiting with exit-code 125"
+              exit 125
+            fi
+
+  build:
+    # TODO: Split me into separate Frontend and Backend builds
+    working_directory: /home/circleci/app
+    resource_class: large
     docker:
       - image: cimg/python:3.7-node
         environment:
-          SQLALCHEMY_DATABASE_URI: postgresql://taskingmanager@localhost/tm_test
+          SQLALCHEMY_DATABASE_URI: postgresql://taskingmanager@localhost/test_tm
       - image: cimg/postgres:14.7-postgis
         environment:
           POSTGRES_USER: taskingmanager
-          POSTGRES_DB: tm_test
+          POSTGRES_DB: test_tm
     steps:
       - checkout
       - setup_remote_docker
@@ -27,7 +67,6 @@ jobs:
       - run:
           name: Configure Postgresql Test database
           command: |
-            echo "User: $POSTGRES_USER ; Database: $POSTGERS_DB"
             sudo apt-get install postgresql-client
             psql -h localhost -U $POSTGRES_USER test_$POSTGRES_DB -c "CREATE EXTENSION postgis;"
       - run:
@@ -82,83 +121,6 @@ jobs:
           paths:
             - frontend/node_modules
             - env
-    # The resource_class feature allows configuring CPU and RAM resources for each job. Different resource classes are available for different executors. https://circleci.com/docs/2.0/configuration-reference/#resourceclass
-    resource_class: large
-
-  backend-deploy-test:
-    parameters:
-      stack_name:
-        description: "the name of the stack for cfn-config"
-        type: string
-    working_directory: /home/circleci/tasking-manager
-    resource_class: medium
-    docker:
-      - image: cimg/python:3.7
-    steps:
-      - checkout
-      - setup_remote_docker
-      - aws-cli/setup:
-          role-arn: "arn:aws:iam::$ORG_AWS_ACCOUNT_ID:role/CircleCI-OIDC-Connect"
-          profile-name: "OIDC-Profile"
-          role-session-name: "backend-deploy"
-          session-duration: "2700"
-      - run:
-          name: Install modules
-          command: |
-            sudo apt-get update
-            sudo apt-get install -y libgeos-dev jq # Required for shapely
-      - run:
-          name: Get RDS Instance ID
-          command: |
-            chmod +x .circleci/rdsid.sh
-            RDS_ID=$(./.circleci/rdsid.sh '{"aws:cloudformation:stack-name": "tasking-manager-<< parameters.stack_name >>"}')
-            echo "$RDS_ID"
-      - run:
-          name: Remove last snapshot and backup database
-          no_output_timeout: 15m
-          command: |
-            aws --version
-            DESCRIBE_SNAPSHOT=$(aws rds describe-db-snapshots --db-snapshot-identifier tm3-<< parameters.stack_name >>-$RDS_ID-latest --db-instance-identifier $RDS_ID --output text)
-            NONCE=$(openssl rand -hex 4)
-            echo "export NONCE=$NONCE" >> $BASH_ENV
-            echo "$DESCRIBE_SNAPSHOT"
-      - run:
-          name: Cleanup
-          when: always
-          command: |
-            aws --version
-            DESCRIBE_SNAPSHOT=$(aws rds describe-db-snapshots --db-snapshot-identifier tm3-<< parameters.stack_name >>-${RDS_ID}-${NONCE} --db-instance-identifier ${RDS_ID} --output text)
-            RDS_ID_NEW=$(./.circleci/rdsid.sh '{"aws:cloudformation:stack-name": "tasking-manager-<< parameters.stack_name >>"}')
-            echo "$RDS_ID_NEW"
-
-  frontend-deploy-test:
-    working_directory: /home/circleci/tasking-manager
-    resource_class: large
-    docker:
-      - image: cimg/node:16.20
-    parameters:
-      stack_name:
-        description: "the name of the stack for cfn-config"
-        type: string
-    steps:
-      - checkout
-      - setup_remote_docker
-      - aws-cli/setup:
-          role-arn: "arn:aws:iam::$ORG_AWS_ACCOUNT_ID:role/CircleCI-OIDC-Connect"
-          profile-name: "OIDC-Profile"
-          role-session-name: "frontend-deploy"
-          session-duration: "1800"
-      - run:
-          name: Deploy Frontend to S3
-          command: |
-            cd ${CIRCLE_WORKING_DIRECTORY}/frontend/
-            export TM_ENVIRONMENT=<< parameters.stack_name >>
-            yarn
-            CI=true GENERATE_SOURCEMAP=false yarn build
-            aws s3 sync build/ s3://tasking-manager-<< parameters.stack_name >>-react-app --delete --cache-control max-age=31536000
-            aws s3 cp s3://tasking-manager-<< parameters.stack_name >>-react-app s3://tasking-manager-<< parameters.stack_name >>-react-app --recursive --exclude "*" --include "*.html" --metadata-directive REPLACE --cache-control no-cache --content-type text/html
-            export DISTRIBUTION_ID=$(aws cloudformation list-exports --output=text --query "Exports[?Name=='tasking-manager-<< parameters.stack_name >>-cloudfront-id-${AWS_REGION}'].Value")
-            aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*"
 
   backend_deploy:
     parameters:
@@ -187,41 +149,7 @@ jobs:
             sudo apt-get install -y libgeos-dev jq # Required for shapely
             sudo yarn global add @mapbox/cfn-config @mapbox/cloudfriend
             pip install awscli --upgrade
-      - run:
-          name: Get RDS Instance ID
-          command: |
-            chmod +x .circleci/rdsid.sh
-            RDS_ID=$(./.circleci/rdsid.sh '{"aws:cloudformation:stack-name": "tasking-manager-<< parameters.stack_name >>"}')
-            echo "export RDS_ID=$RDS_ID" >> $BASH_ENV
-      - run:
-          name: Remove last snapshot and backup database
-          no_output_timeout: 15m
-          command: |
-            DESCRIBE_SNAPSHOT=$(aws rds describe-db-snapshots --db-snapshot-identifier tm3-<< parameters.stack_name >>-$RDS_ID-latest --db-instance-identifier $RDS_ID --output text)
-            NONCE=$(openssl rand -hex 4)
-            echo "export NONCE=$NONCE" >> $BASH_ENV
-            # Copy old snapshot to temporary
-            if [ -z "$DESCRIBE_SNAPSHOT" ]
-            then
-                echo "Snapshot does not exist, creating one now."
-            else
-                aws rds copy-db-snapshot \
-                        --source-db-snapshot tm3-<< parameters.stack_name >>-${RDS_ID}-latest \
-                        --target-db-snapshot tm3-<< parameters.stack_name >>-${RDS_ID}-${NONCE}
-                aws rds delete-db-snapshot \
-                        --db-snapshot-identifier tm3-<< parameters.stack_name >>-${RDS_ID}-latest
-            fi
-            # create new aws rds snapshot
-            aws rds create-db-snapshot \
-                        --db-snapshot-identifier tm3-<< parameters.stack_name >>-${RDS_ID}-latest \
-                        --db-instance-identifier ${RDS_ID}
-            aws rds wait db-snapshot-completed \
-                        --db-snapshot-identifier tm3-<< parameters.stack_name >>-${RDS_ID}-latest \
-                        --db-instance-identifier ${RDS_ID}
-            if [[ $? -eq 255 ]]; then
-              echo "Production snapshot creation failed. Exiting with exit-code 125"
-              exit 125
-            fi
+
       - run:
           name: Download config file
           command: |
@@ -234,24 +162,6 @@ jobs:
             validate-template $CIRCLE_WORKING_DIRECTORY/scripts/aws/cloudformation/tasking-manager.template.js
             export JSON_CONFIG="$(cat $CIRCLE_WORKING_DIRECTORY/cfn-config-<< parameters.stack_name >>.json)"
             cfn-config update << parameters.stack_name >> $CIRCLE_WORKING_DIRECTORY/scripts/aws/cloudformation/tasking-manager.template.js -f -c hot-cfn-config -t hot-cfn-config -r $AWS_REGION -p "$JSON_CONFIG"
-      - run:
-          name: Cleanup
-          when: always
-          command: |
-            DESCRIBE_SNAPSHOT=$(aws rds describe-db-snapshots --db-snapshot-identifier tm3-<< parameters.stack_name >>-${RDS_ID}-${NONCE} --db-instance-identifier ${RDS_ID} --output text)
-            # Copy old snapshot to temporary
-            if [ -z "$DESCRIBE_SNAPSHOT" ]
-            then
-              echo "temporary snapshot doesn't exist, nothing to cleanup."
-            else
-              aws rds delete-db-snapshot --db-snapshot-identifier tm3-<< parameters.stack_name >>-${RDS_ID}-${NONCE}
-            fi
-            # Delete manual snapshot if database ID changed
-            RDS_ID_NEW=$(./.circleci/rdsid.sh '{"aws:cloudformation:stack-name": "tasking-manager-<< parameters.stack_name >>"}')
-            if [ "$RDS_ID" != "$RDS_ID_NEW" ]
-            then
-              aws rds delete-db-snapshot --db-snapshot-identifier tm3-<< parameters.stack_name >>-${RDS_ID}-latest
-            fi
 
   frontend_deploy:
     working_directory: /home/circleci/tasking-manager
@@ -279,34 +189,144 @@ jobs:
             CI=true GENERATE_SOURCEMAP=false yarn build
             aws s3 sync build/ s3://tasking-manager-<< parameters.stack_name >>-react-app --delete --cache-control max-age=31536000
             aws s3 cp s3://tasking-manager-<< parameters.stack_name >>-react-app s3://tasking-manager-<< parameters.stack_name >>-react-app --recursive --exclude "*" --include "*.html" --metadata-directive REPLACE --cache-control no-cache --content-type text/html
-            export DISTRIBUTION_ID=`aws cloudformation list-exports --output=text --query "Exports[?Name=='tasking-manager-<< parameters.stack_name >>-cloudfront-id-${AWS_REGION}'].Value"`
+            export DISTRIBUTION_ID=$(aws cloudformation list-exports --output=text --query "Exports[?Name=='tasking-manager-<< parameters.stack_name >>-cloudfront-id-${AWS_REGION}'].Value")
             aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*"
 
 workflows:
   version: 2
 
-  circleci-test:
+  production-all:
+    when:
+      and:
+        - equal: [ deployment/hot-tasking-manager, << pipeline.git.branch >> ]
+    jobs:
+      - database-snapshot:
+          name: Backup production database
+          stack_name: "tm4-production"
+      - build
+      - backend_deploy:
+          name: backend-production
+          stack_name: "tm4-production"
+          requires:
+            - build
+            - database_snapshot
+          gitsha: $CIRCLE_SHA1
+          context:
+            - org-global
+            - tasking-manager-tm4-production
+      - frontend_deploy:
+          name: frontend-production
+          stack_name: "tm4-production"
+          requires:
+            - build
+          context:
+            - org-global
+            - tasking-manager-tm4-production
+
+  production-frontend:
+    when:
+      and:
+        - equal: [ deployment/hot-tasking-manager-frontend, << pipeline.git.branch >> ]
+    jobs:
+      - build
+      - frontend_deploy:
+          stack_name: "tm4-production"
+
+  staging-all:
+    when:
+      or:
+        - equal: [ develop, << pipeline.git.branch >> ]
+        - equal: [ staging-test, << pipeline.git.branch >> ]
+    jobs:
+      - database-snapshot:
+          name: Backup staging database
+          stack_name: "staging"
+      - build
+      - backend_deploy:
+          stack_name: "staging"
+          gitsha: $CIRCLECI_SHA1
+      - frontend_deploy:
+          stack_name: "staging"
+
+  teachosm-all:
+    when:
+      and:
+        - equal: [ deployment/teachosm-tasking-manager, << pipeline.git.branch >> ]
+    jobs:
+      - database-snapshot:
+          name: Backup TeachOSM database
+          stack_name: "teachosm"
+      - build
+      - backend_deploy:
+          name: Deploy TeachOSM Backend
+          stack_name: "teachosm"
+          requires:
+            - build
+          gitsha: $CIRCLECI_SHA1
+          context: tasking-manager-teachosm
+      - frontend_deploy:
+          name: Deploy TeachOSM Frontend
+          stack_name: "teachosm"
+          requires:
+            - build
+          context: tasking-manager-teachosm
+
+  tm-assisted-all:
+    when:
+      and:
+        - equal: [ deployment/assisted-tasking-manager, << pipeline.git.branch >> ]
+    jobs:
+      - database-snapshot:
+          name: Backup TM Assisted database
+          stack_name: "assisted"
+      - build
+      - backend_deploy:
+          name: Deploy TM Assisted Backend
+          stack_name: "assisted"
+          requires:
+            - build
+          gitsha: $CIRCLECI_SHA1
+          context: tasking-manager-assisted
+      - frontend_deploy:
+          name: Deploy TM Assisted Frontend
+          stack_name: "assisted"
+          requires:
+            - build
+          context: tasking-manager-assisted
+
+  development-staging-all:
+    when:
+      or:
+        - equal: [ develop, << pipeline.git.branch >> ]
+        - equal: [ staging-test, << pipeline.git.branch >> ]
     jobs:
       - build:
-          context: org-global
-          filters:
-            branches:
-              only: staging-test
-
-      - frontend-deploy-test:
-          context: org-global
+          context: tasking-manager-testing
+      - backend_deploy:
+          name: Deploy development/staging backend
           stack_name: "staging"
-          filters:
-            branches:
-              only: staging-test
-
-      - backend-deploy-test:
-          context: org-global
+          requires:
+            - build
+          gitsha: $CIRCLE_SHA1
+          context:
+            - org-global
+            - tasking-manager-staging
+      - frontend_deploy:
+          name: Deploy development/staging frontend
           stack_name: "staging"
-          filters:
-            branches:
-              only: staging-test
+          requires:
+            - build
+          context:
+            - org-global
+            - tasking-manager-staging
 
-notify:
-  webhooks:
-    - url: https://api.opsgenie.com/v1/json/circleci?apiKey=$OPSGENIE_API
+  build-only-all:
+    when:
+      not:
+        matches:
+          pattern: "^deployment/.*"
+          value: << pipeline.git.branch >>
+    jobs:
+      - build:
+          context: tasking-manager-testing
+
